services:
  postgres:
    image: postgres:latest
    container_name: snowflake
    environment:
      POSTGRES_USER: snowflake_user
      POSTGRES_PASSWORD: snowflake123
      POSTGRES_DB: snowflake
    volumes:
      - ./исходные данные:/data
      - ./migrations:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pgdata:
  pgadmin_data: